spring.application.name=springboot1-9
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false

# Kết nối CSDL SQL Server (Hỗ trợ tiếng Việt Unicode)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webst9;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_nationalized_character_data=true

# Spring Configuration
spring.main.allow-bean-definition-overriding=true
